[package]
description = "Sjónvarpsdagskrá RÚV"
edition = "2021"
name = "dagskra"
version = "0.2.0"

[dependencies]
askama = { version = "0.12.0", features = ["with-axum"] }
askama_axum = "0.3.0"
axum = "0.6.19"
chrono = "0.4.26"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.97"
shuttle-axum = "0.21.0"
shuttle-runtime = "0.21.0"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
