[package]
description = "What's on Icelandic TV today"
edition = "2021"
name = "dagskra"
version = "0.1.0"

[dependencies]
askama = {version = "0.11", default-features = false, features = ["with-axum"]}
askama_axum = {version = "0.2"}
axum = "0.6"
chrono = "0.4"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = {version = "1", features = ["full"]}
