[package]
description = "Sjónvarpsdagskrá RÚV"
edition = "2021"
name = "dagskra"
version = "0.2.0"

[dependencies]
askama = { version = "*", features = ["with-axum"] }
askama_axum = "*"
axum = "*"
chrono = "*"
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
shuttle-axum = "*"
shuttle-runtime = "*"
tokio = { version = "*", features = ["full"] }
tracing = "*"
