[package]
description = "Sjónvarpsdagskrá RÚV"
edition = "2021"
name = "dagskra"
version = "0.3.1"

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
axum = "0.7.2"
chrono = "0.4.31"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
